# Generated by Django 6.0 on 2026-01-23 03:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('kategori', models.CharField(choices=[('bangunan', 'Bangunan'), ('jalan', 'Jalan'), ('perairan', 'Perairan'), ('pepohonan', 'Pepohonan')], max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('confidence_score', models.FloatField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
