# Generated by Django 5.2.10 on 2026-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('kategori', models.CharField(choices=[('bangunan', 'Bangunan'), ('jalan', 'Jalan'), ('perairan', 'Perairan'), ('pepohonan', 'Pepohonan')], max_length=50)),
                ('geom_data', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
